### ISSUE TITLE
invalid_client probléma - pontosan mit is jelent ez?

### ISSUE THREAD

**Issue by WilliamNT** [bczsalba/ekreta-docs-v3#12]
Sziasztok! Az invalid_client hiba a `clientId`-ra vonatkozik vagy csak egy rosszul megfogalmazott hiba ami arra utal, hogy elutasítja a kérést a klienstől ami a kérést küldte? (bár akkor már `invalid_request`-et kéne dobjon, nem?).

Az alábbi kódom elméletben működik, de a gyakorlatban a fent említett `invalid_client` hibát kapom vissza. Én a HMAC aláírós részre gyanakszok, nem értek hozzá, szóval simán lehet, hogy ott bukik el a dolog.

Releváns kód részlet: https://github.com/WilliamNT/JavaKreta_Wrapper

**Comment by FightMan01** [comment]
Szia, tudom kicsit késő, de utánna jártam: #13
