### ISSUE TITLE
Response: 301 Moved Permanently

### ISSUE THREAD

**Issue by winux1** [bczsalba/ekreta-docs-v3#4]
Szia!

Nagyon örülök, hogy felujítottad boa dokumentációját! Viszont amikor valamit le szeretnék kérdezni curl-lel a Bearer kódon kívül Ezt kapom:

Futtatott kód: `curl -H "Authorization: Bearer $Bearer" -H 'User-Agent: hu.ekreta.student/1.0.5/Android/0/0' "https://klik035327001.ekreta.hu/ellenorzo/V3/Sajat/OrarendElemek"`

Eredmény:
```html
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
Van valami ötleted hogy miért történik ez?

**Comment by bczsalba** [comment]
Szia!

Megpróbáltam a saját sulimmal, és nekem működik, ahogy kéne. A te parancsodnak válaszul egy `Ismeretlen hiba történt!` kéne hogy érkezzen, és mivel ez nem történik szerintem el sem jut a szerverig.

A Kréta appok, illetve a Filc működnek a sulitokban? tudtommal ugyanazt a módszert használják, mint ami itt van dokumentálva.

Annyit próbálj meg, hogy `ekreta.hu` helyett`e-kreta.hu`-t írsz, nem hiszem, hogy működni fog, de egy próbát megér.

**Comment by winux1** [comment]
Kösznöm a válaszod! Kicseréltem `e-kreta`-ra, így mostmár jó!

Az issue-t zárom.

**Comment by bczsalba** [comment]
Hozzáadtam egy disclaimer-t a doc-hoz erről, köszönöm hogy felhoztad!

**Comment by winux1** [comment]
> Hozzáadtam egy disclaimer-t a doc-hoz erről, köszönöm hogy felhoztad!

Én köszönöm hogy segítettél!
