### ISSUE TITLE
Átlag lekérése a mobil api segítségével

### ISSUE THREAD

**Issue by moldender** [bczsalba/ekreta-docs-v3#5]
Sziasztok!

1-2 hónapja elkezdtem egy discord botot és abba szerettem volna egy átlag lekérési funkciót, habár ez nem működött annyira hiszen ez csak fogja a jegyeket és hogy mennyi van belőlük és elosztja őket, a súlyszázalékot nem tudtam megoldani. Viszont nemrég kísérletezgettem a weboldalon lévő api-okkal, de azok cookie-s azonosítást használtak sok helyen. De találtam egy postmanes dokumentációt és látván hogy nincs átlag / az osztályátlag nem működik gondoltam megmutatom amit találtam (hisz a postmanes nem teljesen működött).

headers:

{
    'Authorization': xxxxxx (acces token),
    'Accept-Encoding': 'gzip, gzip',
    'Accept': 'application/json',
    'User-Agent': 'hu.ekreta.student',
    'Host': 'xxxxxxx.e-kreta.hu',
}

a request: https://xxxxxxx.e-kreta.hu:443/mapi/api/v1/TantargyiAtlagAmi

**és nemtudom de nekem egy sima access tokennel nem működött szóval itt van az access token requestje:**

headers:

{
    'Content-Type': 'application/x-www-form-urlencoded',
    'User-Agent': 'hu.ekreta.student/1.0.5/Android/0/0',
}

data:

{
    'userName': xxxxxx,
    'password': xxxxxxx,
    'institute_code': xxxxxx,
    'grant_type': 'password',
    'client_id': '919e0c1c-76a2-4646-a2fb-7085bbbf3c56'    **#ez mindenkinél ugyanaz**
}

a request: https://xxxxxxx.e-kreta.hu/idp/api/v1/Token

és még egy pár sor kóddal 100%ig pontosan tudtam mutatni mindenki átlagát :D
(még kezdő vagyok az api-okkal kapcsolatban, ha valami kérdésetek van írjatok)

**Comment by bczsalba** [comment]
Szia! Ez tök érdekes, még nem láttam.

A request csak a 443-as porton működik? Ha igen, akkor lehet nem használt/tesztelésben lévő endpoint, ami nem feltétlenül megbízható.

A kódot amit használsz egy egész átlag lekérése során meg tudnád mutatni?

Köszönöm!
Balázs

**Comment by moldender** [comment]
Heló! Bocsi későn láttam a kommented, én a 443-as an próbáltam, ezt mutatta nekem az ssl cpature amit a mApi dokumentációjához is használtak. Én így tudom hogy ez már legalább egy éve bent van a krétába és így kéri le a mobilos átlagokat. A web api túl bonyolult volt és egy __requestverificationtoken is kellett annak a lekéréséhez ezért maradtam a mobil api-nál. És hát igazából így kérem le az egész átlagot(jó, persze még megoldom hogy megszámolja a tantárgyakat és az átlagok összegét elossza vele pythonba xd). Ha kész lesz a botom teljesen akkor egyébként lehet hogy open source-á teszem.

A response az átlagra a következő ([a postmanes dokumentációból küldöm](https://documenter.getpostman.com/view/10379752/SzKPULz6#9d69acbb-b6fb-457c-9b18-6587597094cd) :

{
    "StudentId": 0,
    "SchoolYearId": 0,
    "Name": "Xxxxxx Xxxxx",
    "NameOfBirth": "Xxxxxx Xxxxx",
    "PlaceOfBirth": "Xxxxxxxxx",
    "MothersName": "Xxxxxx Xxxxx",
    "AddressDataList": [
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "..."
    ],
    "DateOfBirthUtc": "2069-04-20T09:38:23",
    "InstituteName": "Xxxxxx Xxxxx",
    "InstituteCode": "Xxxxxxxxx",
    "Evaluations": [
        {
            "EvaluationId": 0,
            "Form": "Xxxx",
            "FormName": "Xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "Type": "Xxxxxx",
            "TypeName": "Xxxxxx",
            "Subject": "Xxxxxx xxxxx",
            "SubjectCategory": null,
            "SubjectCategoryName": "Xxxxxx",
            "Theme": "Xxxxx",
            "IsAtlagbaBeleszamit": true,
            "Mode": "Xxxxxx",
            "Weight": "0%",
            "Value": "Xxxxxx",
            "NumberValue": 0,
            "SeenByTutelaryUTC": null,
            "Teacher": "Xxxxx Xxxxx",
            "Date": "2069-04-20T09:38:23",
            "CreatingTime": "2069-04-20T09:38:23",
            "Jelleg": {
                "Id": 0,
                "Nev": "Xxxxxx",
                "Leiras": "Xxxxxxx"
            },
            "JellegNev": "Xxxxxx",
            "ErtekFajta": {
                "Id": 0,
                "Nev": "Xxxxxxx",
                "Leiras": "XXxxxxxx"
            },
            "OsztalyCsoportUid": "000000"
        },
        {...}
    ],
    "SubjectAverages": null, //A ".../Lesson" API itt visszaadja a tantárgyi átlagokat
    "Absences": [
        {
            "AbsenceId": 0,
            "Type": "Xxxxxx",
            "TypeName": "Xxxxxx",
            "Mode": "Xxxxx",
            "ModeName": "Xxxxx xxxxxx",
            "Subject": "xxxxx",
            "SubjectCategory": null,
            "SubjectCategoryName": "Xxxxx",
            "DelayTimeMinutes": 0,
            "Teacher": "Xxxxxxx Xxxxxxx",
            "LessonStartTime": "2069-04-20T09:38:23",
            "NumberOfLessons": 0,
            "CreatingTime": "2069-04-20T09:38:23",
            "JustificationState": "Xxxxxxx",
            "JustificationStateName": "Xxxxxx xxxxx",
            "JustificationType": "Xxxxxxx",
            "JustificationTypeName": "Xxxxx xxxxx",
            "SeenByTutelaryUTC": null,
            "OsztalyCsoportUid": "000000"
        },
        {...}
    ],
    "Notes": [
        {
            "NoteId": 0,
            "Type": "Xxxxxxx",
            "Title": "Xxxxxxx",
            "Content": "Xxxxxx xxxxx xxxx xxxxxxxx xxx xxx",
            "SeenByTutelaryUTC": null,
            "Teacher": "Xxxxx Xxxx Xxxxx",
            "Date": "2069-04-20T09:38:23",
            "CreatingTime": "2069-04-20T09:38:23",
            "OsztalyCsoportUid": "000000"
        },
        {...}
    ],
    "OsztalyCsoportok": [ //Teljesen más felépítés, mint a ".../Lesson API-nál"
        {
            "OktatasNevelesiFeladat": {
                "Uid": "0000",
                "Leiras": "Xxxxxxx",
                "Nev": "xxxxxxx"
            },
            "OktatasNevelesiKategoria": {
                "Uid": "0000",
                "Leiras": "Xxxxxx xxxx",
                "Nev": "Xxxxx xxxxxx"
            },
            "Nev": "xxxxxx",
            "OsztalyCsoportTipus": "xxxxxx",
            "IsAktiv": true,
            "Uid": "000000",
            "OsztalyfonokUid": "000000"
        },
        {...}
    ],
    "Lessons": null,
    "Events": null,
    "FormTeacher": null, //itt null, ".../Lesson" API-nál van (egyébként teljesen felesleges) adat
    "Osztalyfonokok": [
        {
			"Uid": "000000",
            "Tanar": {
                "Uid": "000000",
                "Alkalmazott": {
                    "Uid": "000000",
                    "Nev": "Xxxx Xxxxx",
                    "Telefonok": [],
                    "Emailek": []
                }
            },
            "Osztalyai": [
                {
                    "Uid": "000000",
                    "Nev": "Xxxx"
                }
            ]
        },
        {...}
    ],
    "Tutelaries": [
        {
            "TutelaryId": 00000,
            "Name": "Xxxxx",
            "Email": "xxxxxxxxxxxxxxxxxx",
            "PhoneNumber": "0000000000"
        },
		{...}
    ]
}

**Comment by bczsalba** [comment]
Na bocsanat, elkapott az erettsegi szezon az elozo kommentem ota.

A postman dokumentacio egy masik API-hoz szol mint ez, szoval az altalad adott endpoint gyakorlatilag nem ennek az API-nak a resze.

Azon kivul erdekes, es segitett egy masik problema megoldasaban, szoval koszonjuk!
