### ISSUE TITLE
Valaki megtudná mondani hogyan tudok üzenetet küldeni?

### ISSUE THREAD

**Issue by WilliamNT** [bczsalba/ekreta-docs-v3#7]
Tehát azt értem hogy hogy megvan az endpoint AdminEndpoints osztály alatt, de hogyan és milyen formátumban küldjek adatot?
Formátum alatt arra gondolok hogy JSON? Ha igen, hogyan nézzen ki ez a JSON?

Előre is köszi!

**Comment by moldender** [comment]
Én megpróbáltam, az id-ket meg egyéb azonosítókat nem tudom mondani hogy hogyan kell megszerezni de itt a formátuma. (a csatalomány opcionális, és az `utvonal` pedig az aznapi nap szerintem. Az azonosító szerintem hogy kinek küldöd, az én tanáraimnál ez egy 9.-es volt. Cs) 

```json
{
   "targy":"xxxx",
   "szoveg":"xxxx",
   "elozoUzenetAzonosito":null,
   "cimzettLista":[
      {
         "azonosito":null,
         "nev":"xxxx xxxx",
         "kretaAzonosito":"xxxx",
         "tipus":{
            "azonosito":9,
            "kod":"TANAR",
            "rovidNev":"Tanár",
            "nev":"Tanár",
            "leiras":"Tanár"
         },
         "idpEgyediAzonosito":"xxxx-xxxx-xxxx-xxxx-xxxx",
         "egyediAzonosito":"xxxx-xxxx-xxxx-xxxx-xxxx"
      }
   ],
   "csatolmanyok":[
      {
         "fajlNev":"xxxx.xxxx",
         "fajl":{
            "azonosito":null,
            "ideiglenesFajlAzonosito":"xxxx-xxxx-xxxx-xxxx-xxxx",
            "utvonal":"20211014",
            "fileHandler":"FileService"
         },
         "iktatoszam":null
      }
   ]
}
```

**Comment by WilliamNT** [comment]
Rendben, köszi! Majd ránézek ha haza értem. `"targy":"xxxx"`-nál melyik név kell? Rövidnév, leírás (vagy amik vannak, most nem tudom fejből)?
